languageCode = "en-us"
title = "Kiali"
theme = "canvas"

[params]
    custom_css = [
      "/css/kiali_style.css",
      "https://use.fontawesome.com/releases/v5.3.1/css/all.css"
    ]
    maxBlogPosts   = 10

    latest = "1.0"
    binariesLatest = "1.0"
    versions = ["1.0"]

[menu]
  [[menu.main]]
      identifier = "documentation"
      name = "Docs"
      url = "/docs"
      weight =  30